# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ content: market.png"
Post.create [

{content: "Robin said hi to me!"},
{content: "I jogged for the first time in years.... gym sessions are paying off it seems!!"},
{content: "Today was great because I woke up and had intimate and funny conversation with my beautiful girlfriend while listening to sounds of nature from our tent."},
{content: "Ran 6 miles without walking!"},
{content: "Today was great because I had no homework! With my newly freed time, I volunteered at my library."},
{content: "I got to clear my mind with yoga, then spend the rest of the morning with my darling horse :]"},
{content: "Today was great because I finally got word that I have an engine for my car that has been out of action for almost 3 months :) can't wait to drive my car again."},
{content: "Having a healthy check up for my daughter made my day great.  I often think about how hugely good health is taken for granted, so I'm trying to think about it and appreciate it more regularly!"},
{content: "Today was great because I had a heart-to-heart with someone very close to me and it made me see things in a whole new light.  It's good to be reminded that there are many different sides to one situation and it's important to consider them all!"},
{content: "A really happy song that I like came on the radio while I was driving (alone) and I sang it loudly!"},
{content: "Since my husband has 2 weeks off between work ending and grad school starting, we're getting to reverse our roles and gain a whole new appreciation for each other!  I can't say I mind having dinner on the table when I get home from work!"},
{content: "I had a really horrible dream that my dad had cancer... but then got to wake up from it."},
{content: "I submitted the final copy of something for work that I've been working on non-stop."},
{content: "Today was great because my daughter learned howcontente 'pucker' sound when giving a kiss... it was a long evcontentm 'dog licks' to pressing her lips without any sound or movement... but she is now giving official (and oh-so-sweet) smooches."},
{content: "The post below helped mcontenty 'today was great' moment.... On a 6 mile bike ride, I got to a pretty steep hill, and I kept sayicontentf 'you can do it, you can do it' and one pedal at a time, made it to the top and got to sail down the other side.  I thought for sure I'd have to walk it, but I made it and felt so proud to have pushed myself!"},
{content: "I ran uphill and kept running. I was slow, but I did it. Whew!"},
{content: "Today I held a 3 day old baby and it reminded me how quickly children grow.  So, instead of going to bed at her normal time, my one year old and I rolled around giggling for an extra half an hour as I breathed in every ounce of her youthfulness."},
{content: "Right before settling for some frozen food for lunch, I remembered I had leftovers from my favorite restaurant in the fridge!"},
{content: "Today was great because the early morning included many giggles and funny conversation with my beau."},
{content: "Today was great because it was the 5th day in a row that my wonderful girlfriend sent me off to work with a packed lunch and a love note."},
{content: "Because i get to hang out with some amazing friends!!"},
{content: "I sent out an important email today and it made me feel proud."},
{content: "Today was great because after a yummy dinner with just my two year old ( hubby worked late) she put her head on my shoulcontentd 'thank you,mommy I love you'  as to thank me for the effort of making us dinner. And then to interrupt content. 'cookie please, mommy.'"},
{content: "Today was great because I had my in-laws over for dinner and it made my husband happy."},
{content: "Watching Queensland win the State of Origin for the Seventh year in a row!! Hells yeah!!"},
{content: "Today was great because I walked arm in arm down the boardwalk with a big group of amazing girlfriends on a warm summer night."},
{content: "I looked out the kitchen window this evening to catch the most gorgeous sky I've ever seen... cotton candy clouds strewn across an almost-transparent early-evening moon."},
{content: "Today was great because the balmy night and lightning bugs have officially made it feel like summer."},
{content: "My husband came food shopping with me and our daughter; what I'd normally consider an errand turned into a really fun family event with him there."},
{content: "Today was great because I read this article about a person risking their life to save that of a baby's who had been blown onto subway tracks by a gust of wind.   It made me love humanity and get a bit choked up."},
{content: "My two year daughter danced to the music of the ice cream truck and then promptlycontenta 'dance truck'!!!!!"},
{content: "Today was great not because I won money at the horse track, but because my dad did."},
{content: "Today was great because after a series of many mishaps, we still were able to enjoy an adventure together."},
{content: "While I had to wait 28 years to go to my first drive-in theater, my daughter got to experience it before her 1st birthday! That made today great."},
{content: "Today was great because I made time to read a book that I'm really enjoying."},
{content: "I made it down to Florida with my baby so she could meet her great-grandma for the first time; she's 97 so you never know!"},
{content: "I got to surprise my brother with tickets to see a show I knew he'd really love to go to"},
{content: "Today was great because I got to see a close friend get showered with love."},
{content: "Today was great because my daughter took her first steps- and my husband was there to see it!"},
{content: "Its half-day friday!"},
{content: "I kissed a beautiful woman this morning!"},
{content: "Organised my own birthday party... should be fun!"},
{content: "I painted my bedroom and it looks great!"},
{content: "We took our baby on an airplane for the first time and she did SO well that now we feel comfortable to start traveling again!"},
{content: "Today was great because I sat in a hotel room with my husband, eating Thai food and drinking wine as we watched a huge lightning storm."},
{content: "I had a wonderful family day!"},
{content: "Watching my 10 montcontente 'out came the sun' hand motion when we sang the Itsy Bitsy Spider."},
{content: "I got myself a new bike!"},
{content: "Today was great because my brother came to visit!"},
{content: "I stayed up real late with a super-special girl, laughing, chatting, and taking silly pictures, after she made us a delicious hot meal."},
{content: "Walking on the boardwalk on a day with perfect weather!"},
{content: "My sister going out of her way to drop off vegan shepherd's pie and cake just because she knew I needed it."},
{content: "Today was great because I got to watch Three Amigos. I love Three Amigos."},
{content: "Watching my wife hang out with an old friend and seeing how happy it made her."},
{content: "Today was great because I got to make dinner for my best friend and have a nice, very long chat."},
{content: "My friend shared his food with me that looked (and tasted) sooo good. Thank you :)"},
{content: "Today was great because I got a new shirt that I really like (and I never buy anything new)."},
{content: "Today was great because I made it back from my business trip safely."},
{content: "Today was great because I went for a bike ride."},
{content: "Today was great [so far}, because no one is in my office today, it's nice and peaceful, my music is playing, and I am getting loads of work done! [a.k.a. shopping for summer clothes and other fabulous items online!] Yay summer!"},
{content: "Just booked some flights to NY for my birthday.. which also means that I get to go to a very special persons 1st Birthday!! YAY!"},
{content: "I found out that a very good friend may be coming to visit from the other side of the world to spend his 30th birthday with us!!!!!"},
{content: "Today was great because there was a warm summer rain and it reminded me of being younger than a teenager"},
{content: "I have been given the night off work.. whats not to like about that!!!"},
{content: "I saw a blue bird in the yard and it made me happy."},
{content: "My husband and I went to a really fun show where everyone was so squished in together, that the crowd was jumping in unison. Being tall and holding me close, he helped me jump a lot higher (as with everything in my life)."},
{content: "Today was great because my best friend got accepted into school (even though it means she has to move)."},
{content: "When my 10 month daughter caught me staring at her in the mirror as she was falling asleep, she smiled softly and started to wave."},
{content: "Today was great because I got home seconds before a big storm hit."},
{content: "Today was great because I got to lay in the grass on such a beautiful day."},
{content: "Today was great because my daughter is suddenly and rapidly starting to learn, understand and copy many of the words I'm saying to her."},
{content: "After a long history of accidentally and consistently killing plants, I spent the day planting flowers, shrubs and herbs. It feels good to have a little faith in myself and the house looks so lively!"},
{content: "Today was great because the weather was so perfect...what's not to like?"},
{content: "We finally purchased a new fridge to replace our old one from 1979 - goodbye glued-on Formica and hello French doors!!"},
{content: "I started organising some fun things to do for my Birthday!! Yay"},
{content: "Today was great because I produced one of our bigger TV shows at work for the first time."},
{content: "My husband cooked dinner for me and brought it in on a tray because I was too beat to get off the couch."},
{content: "Today I had fancy cocktails with a good friend, sitting outside overlooking Madison Square Park on a perfect (almost) summer night. And he paid. My day was great :)"},
{content: "Today was great because a photographer came up to me and asked to take my picture (though I was too shy to say okay)."},
{content: "Today was great because I got to pick fresh herbs out of my newly planted herb garden to put in my family's dinner."},
{content: "I was feeling really tired today with the gloomy weather, and got to take 2 naps! It felt amazing."},
{content: "Since our air conditioners aren't installed yet, I bought a baby pool and sat with my daughter in it to cool off.  It sure beat sitting inside!"},
{content: "Today was great because after 5 days of being sick, I started feeling better."},
{content: "Today was great because I had my lunch outside on a park bench and then took a nap for half an hour  in the beautiful summer sun."},
{content: "I got to see a band I really like play an intimate, secret show before heading out for tour."},
{content: "Today was great because I sat with friends overlooking the ocean."},
{content: "Today was great because we brought our 10 month old (wearing headphones) to a show... she was clapping along and loved watching the band playing their instruments.  It was nice how many strangers came up to us and said something nice about her being there!"},
{content: "Today was great because my daughter had such a fun first time baby pool experience, she fell asleep for the night at 6 PM!"},
{content: "Today was great because my sister came up for dinner."},
{content: "Today was great because I got to have dinner with my brother, and was reminded how important family time is!"},
{content: "Today was great because when our neighbors saw us starting to build a shed, they came over with tools and helped us build it."},
{content: "Today was great cause I got to spend time with a person I love and I got to see Audrey."},
{content: "I ended my great day sitting outside drinking beers with friends on this warm Spring night."},
{content: "Today was great because my 10 month old took her first step in the morning; and was very social at a friends' BBQ in the evening!"},
{content: "Today was great because when on my walk with my daughter, the birds were enjoying the beautiful day and it officially felt like spring"},
{content: "Today I painted my nails green and it reminded me of watermelons."},
{content: "After not having run since my last marathon, today I found I can still run 11 miles."},
{content: "Today was great because my daughter is finally able to sit up all by herself!"},
{content: "I didn't feel well so spent all day resting."},
{content: "I  spent the day with a great mate.. just relaxing and having a good time"},
{content: "Today I stood under cherry trees in the community garden laden with thousands of ripe cherries, and stuffed my face. The last time I did that was when I lived in Ithaca, NY many years ago. Brought back good memories, and my belly was happy! :)"},
{content: "The weather cleared up just in time for a relaxing game of basketball after a long week at work."},
{content: "I swear I heard my 10 month old dcontent, 'Mama, I love you' today."},
{content: "My husband got called for a job interview that's 8 minutes from home... instead of his current commute of 1.5 hours."},
{content: "Today was great because I finally got my daughter to eat solid food! Apples and carrots- mixed, ofCOURSE! Duh, Mom! &lt;3"},
{content: "Spent the day in a boat on a lake watching people race in row boats. I've got a fun job!"},
{content: "Today was great because I thought of warm memories of my father, who died 3 years ago today."},
{content: "Today was great because school let out early, I got to teach a new class of preschoolers and we painted, one of my classes got cancelled, the kids were unexpectedly respectful, no 5th graders with bad attitudes, long weekend, someone I've been worried about is seeming to do better lately, it's beautiful outside, I'm about to listen to an experimental order of a fantastic album with the girl I love while traveling (and I don't have to drive to boot), I've been told there's a feast in store tonight or tomorrow, Sunday I get to hang with my friends and grill and drink beer, no work Monday, and you can just FEEL summer drawing near.  Life is beautiful."},
{content: "Today was great because last night I realized my friends are there for and save me from myself."},
{content: "Today was great because I ate chia seeds for lunch and loved it"},
{content: "today was great because a old friend just came by"},
{content: "My friends forgave me when I lost track of what was important."},
{content: "Today was great because I got a ton of support for this project! Keep the posts coming!"},
{content: "My five and a half month daughter desperately wants to crawl and yet early this morning, she wound up positioning herself into THE most perfect downward dog yoga position I have EVER seen! Amazing!"},
{content: "Today was great because I walked to the farmers' market where I purchased local and organic asparagus and strawberries. YUM! :)"},
{content: "Today was great because I finally got excited about applying for a new job since graduation."},
{content: "Watched my first home being built!"},
{content: "Found out that a good friend of mine created this amazing website!!"},
{content: "My granddaughter can now giggle when she thinks something is funny! Adorable!"},
{content: "Today was great because I read an engrossing book by a new novelist where the main character eats nothing but saurkraut."},
{content: "Today was great. I am alive."},
{content: "Today was great because I got out of work while it was still light out."},
{content: "2 minutes before leaving the office today, I closed a big sale!"},
{content: "After craving tacos all day at work, I opened my pantry to find all the ingredients to make them for dinner. Nom nom"},
{content: "We celebrated our CEO's departure with delicious food and beer and nice speeches :)"},
{content: "Today was great because I had lunch with a friend."},
{content: "Today was great because someone very close to me accomplished something wonderful!!!"},
{content: "Today was great cause I stumbled upon your website which reminded me to be grateful for life xo"},
{content: "Today was great because American Nightmare announced a NYC date this afternoon."},
{content: "I crowd-surfed for the first time in 10 years."},
{content: "My baby got a tooth!"},
{content: "I found out I was accepted into graduate school today!!!!!!"},
{content: "I received a brand new rain coat for my birthday yesterday and today it was pouring; it was nice to have a reason to stand in the rain."},
{content: "I stared down a table today and saw 30 faces who were all there to celebrate my birthday."},
{content: "A day off was spent hiking and camping with our 9 month old; I spent every minute of this experience in awe over how incredible our lives are."},
{content: "I got to watch my daughter share her toys with friends."},
{content: "I made a friend with a broken heart laugh."},
{content: "Since my husband had to go right from work to class, I surprised him outside with a warm meal and'hello' from his daughter, who he otherwise wouldn't have seen all day."},
{content: "I got to watch my husband help my dad work on a home project; watching them get closer melts my heart."},
{content: "My little one and I drove up to meet my husband for lunch; she slept both ways, leaving me with a few hours of silence to reflect."},
]
